### ISSUE TITLE
How to handle this error....?

### ISSUE THREAD

**Issue by vis2hnu1** [andwatson/decompose_insar_velocities#22]
Dear sir/madam,

Actually, this the first time I am using Matlab. So, I am facing difficulty while deal with errors. I had run the code on the example dataset, It worked but the problem is, I am not able to export them (in geotiff, grd..). Please help how can I rectify it. 

Thanking you in advance,

This is what the error message displays:

Error using matlab.internal.imagesci.netcdflib
The NetCDF library encountered an error during execution of "create" function:
"No such file or directory (2)".

Error in netcdf.create (line 61)
        ncid = matlab.internal.imagesci.netcdflib('create', filename, mode);

Error in grdwrite2 (line 41)
ncid = netcdf.create(file, 'NC_SHARE');

Error in decompose_insar_velocities (line 422)
    grdwrite2(x_regrid,y_regrid,m_up,[par.out_path par.out_prefix '_vU.grd']);

**Comment by andwatson** [comment]
Hello, so I'm guessing it would be that the output file either isn't set, or is trying to save into a directory that doesn't exist.
Check if the output of "[par.out_path par.out_prefix '_vU.grd']" is a reasonable path on your system.

**Comment by vis2hnu1** [comment]
Dear @andwatson sir, 
Thank you for your early help, sir. It is a valid path (out_path = example/outputs/), and I created the outputs folder at the destination location. Now, I tried to save the files in geotiff format, sir.
I got another error message sir:

Error using tifflib
Unable to open TIFF file "example\outputs\example__vU.geo.tif".

Error in Tiff (line 660)
            obj.FileID = tifflib('open',filename,mode);

Error in map.geotiff.internal.writeGeoTiffFile (line 26)
tiffObj = Tiff(filename, writeMode);

Error in geotiffwrite (line 28)
map.geotiff.internal.writeGeoTiffFile( ...

Error in decompose_insar_velocities (line 402)
    geotiffwrite([par.out_path par.out_prefix '_vU.geo.tif'],m_up,georef)

**Comment by vis2hnu1** [comment]
> Hello, so I'm guessing it would be that the output file either isn't set, or is trying to save into a directory that doesn't exist. Check if the output of "[par.out_path par.out_prefix '_vU.grd']" is a reasonable path on your system.

Thank you, sir; it worked.
